//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UShare.MegaDropdown {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class MegaDropdown {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mega_division;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mega_academic;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mega_Units;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(MegaDropdown target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmega_division() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("section");
            this.mega_division = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "mega-content");
            @__ctrl.ID = "mega_division";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmega_academic() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("section");
            this.mega_academic = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "mega-sec-two");
            @__ctrl.ID = "mega_academic";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmega_Units() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("section");
            this.mega_Units = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "mega-sec-three");
            @__ctrl.ID = "mega_Units";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::UShare.MegaDropdown.MegaDropdown @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<section class=\"mega-sec-one\">\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlmega_division();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</section>\r\n\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlmega_academic();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControlmega_Units();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/JavaScript\">\r\n    var currentdiv = \"\";\r\n    var currentdep" +
                        "artment = \"\";\r\n\r\n    function divisionBtn(el) {\r\n        var newSelection = docu" +
                        "ment.getElementById(el);\r\n        var currentSelection = document.getElementById" +
                        "(currentdiv);\r\n        var currentDepartmentSelection = document.getElementById(" +
                        "currentdepartment);\r\n\r\n        if (currentSelection != null) { currentSelection." +
                        "style.display = \"none\"; }\r\n        if (currentDepartmentSelection != null) { cur" +
                        "rentDepartmentSelection.style.display = \"none\"; }\r\n        newSelection.style.di" +
                        "splay = \"table\";\r\n        currentdiv = el;\r\n    }\r\n    function departmentBtn(na" +
                        "me) {\r\n        var newSelection = document.getElementById(name);\r\n        var cu" +
                        "rrentSelection = document.getElementById(currentdepartment);\r\n        var curren" +
                        "tDepartmentSelection = document.getElementById(currentdepartment);\r\n        if (" +
                        "currentSelection != null) { currentSelection.style.display = \"none\"; }\r\n        " +
                        "if (currentDepartmentSelection != null) { currentDepartmentSelection.style.displ" +
                        "ay = \"none\"; }\r\n        newSelection.style.display = \"table\";\r\n        currentde" +
                        "partment = name;\r\n    }\r\n\r\n    /*selection active*/\r\n    var divBtns = document." +
                        "getElementsByClassName(\"btnDivNav\");\r\n    for (var i = 0; i < divBtns.length; i+" +
                        "+) {\r\n        divBtns[i].addEventListener(\"click\", function () {\r\n            va" +
                        "r currentDiv = document.getElementsByClassName(\"navDivActive \");\r\n            if" +
                        " (currentDiv.length > 0) {\r\n                currentDiv[0].className = currentDiv" +
                        "[0].className.replace(\" navDivActive \", \"\");\r\n            }\r\n            this.cl" +
                        "assName += \" navDivActive \";\r\n        });\r\n    }\r\n\r\n\r\n    var deptBtns = documen" +
                        "t.getElementsByClassName(\"btnDeptNav\");\r\n    for (var j = 0; j < deptBtns.length" +
                        "; j++) {\r\n        deptBtns[j].addEventListener(\"click\", function () {\r\n         " +
                        "   var currentDept = document.getElementsByClassName(\"navDeptActive \");\r\n       " +
                        "     if (currentDept.length > 0) {\r\n                currentDept[0].className = c" +
                        "urrentDept[0].className.replace(\" navDeptActive \", \"\");\r\n            }\r\n        " +
                        "    this.className += \" navDeptActive \";\r\n        });\r\n    }\r\n</script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
